spring.application.name=StandUp

spring.datasource.url=jdbc:mysql://localhost:3306/new_exam
spring.datasource.username=root
spring.datasource.password=kasm441999
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
server.port=8000